version: "3"
services:
  api:
    container_name: blockapi
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    ports:
      - "80:80"
    build: .
    depends_on:
      - redis
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis